### ISSUE TITLE
Navigating out of the Trading view should close the Pyth Benchmarks API Stream

### ISSUE THREAD

**Issue by 0xcryptovenom** [AdrenaFoundation/frontend#401]
# Current behavior

- When navigating to the Trading View, the Pyth Benchmarks API Stream is opened.
- When starting navigation (or reloading a page) that is not the Trading view (ie: `/stake`), the Pyth Benchmarks API Stream is not opened.

# Expected behavior

Either:

- To solve https://github.com/AdrenaFoundation/frontend/issues/400, the Pyth Benchmarks API Stream is **always** opened / live.

OR:

- When navigating out of the Trading view (ie, to `/stake`), the Pyth Benchmarks API Stream is terminated - and will be re-opened when the user navigates back to the Trading View (or any other page that requires live updates of token prices).

Loosely related to https://github.com/AdrenaFoundation/frontend/pull/396

**Comment by Adrena-Corto** [comment]
legit issue

**Comment by adrena-orex** [comment]
Should be fixed with new system 🙏
